backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow   # Draft → Review → Publish
locale: "id"                       # Label bawaan tetap Inggris, tapi label koleksi di bawah pakai ID

collections:
  - name: "produk"
    label: "Produk"
    label_singular: "Produk"
    folder: "produk"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} — Rp {{price}}"
    sortable_fields: ["title", "price", "commit_date"]
    view_filters:
      - label: "Harga < 50k"
        field: "price"
        pattern: "^[0-4][0-9]{4}$"
    fields:
      - { label: "Nama", name: "title", widget: "string" }
      - { label: "Harga (angka)", name: "price", widget: "number", value_type: "int", min: 0, step: 500 }
      - { label: "Gambar", name: "image", widget: "image", allow_multiple: false }
      - label: "Detail"
        name: "detail"
        widget: "object"
        fields:
          - { label: "Kategori", name: "category", widget: "select", options: ["Makanan", "Minuman", "Lainnya"] }
          - { label: "Stok", name: "stock", widget: "number", value_type: "int", min: 0 }
      - { label: "Deskripsi", name: "body", widget: "markdown" }
