backend:
  name: git-gateway
  branch: main

# Baris baru untuk memuat file CSS khusus preview
register_preview_style: "/admin/preview-style.css"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "produk"
    label: "Produk"
    label_singular: "Produk"
    description: "Kelola semua produk yang akan ditampilkan di website."
    files:
      - label: "Daftar Produk"
        name: "items"
        file: "_data/produk.json"
        fields:
          - label: "Daftar Semua Produk"
            name: "produk_list"
            widget: "list"
            fields:
              - {label: "Judul Produk", name: "title", widget: "string"}
              - {label: "Gambar Produk", name: "thumbnail", widget: "image"}
              - {label: "Harga", name: "harga", widget: "string", required: false}
              - {label: "Deskripsi", name: "deskripsi", widget: "text", required: false}
