backend:
  name: git-gateway
  branch: main

register_preview_style: "/admin/preview-style.css"
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "produk"
    label: "Produk"
    label_singular: "Produk Baru"
    folder: "produk" # <-- PERUBAHAN PENTING: Menyimpan produk di folder 'produk'
    create: true
    # Baris ini SANGAT PENTING untuk menggunakan template HTML kita
    preview_path: "/admin/preview-template.html"
    fields:
      - {label: "Judul Produk", name: "title", widget: "string"}
      - {label: "Gambar Produk", name: "thumbnail", widget: "image"}
      - {label: "Harga", name: "harga", widget: "string", required: false}
      - {label: "Deskripsi", name: "deskripsi", widget: "text", required: false}
      
